src/MethodicalSupportDisciplines.MVC/Controllers/AuthController.cs
using AutoMapper;
using MethodicalSupportDisciplines.BLL.Interfaces;
using MethodicalSupportDisciplines.MVC.Attributes;
using MethodicalSupportDisciplines.Shared.Dto;
using MethodicalSupportDisciplines.Shared.Dto.AuthDto;
using MethodicalSupportDisciplines.Shared.Responses.Services;
using MethodicalSupportDisciplines.Shared.ViewModels.Forms.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace MethodicalSupportDisciplines.MVC.Controllers;

public class AuthController : Controller
{
    private readonly IMapper _mapper;
    private readonly IAuthService _authService;
    private readonly INotificationService _notificationService;
    private readonly IStringLocalizer<AuthController> _stringLocalization;

    public AuthController(IMapper mapper, IAuthService authService, INotificationService notificationService,
        IStringLocalizer<AuthController> stringLocalization)
    {
        _mapper = mapper;
        _authService = authService;
        _notificationService = notificationService;
        _stringLocalization = stringLocalization;
    }

    [HttpGet]
    [Unauthorized]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Unauthorized]
    public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
    {
        if (!ModelState.IsValid)
        {
            _notificationService.CustomErrorMessage(_stringLocalization["RegisterError"]);
            return View(registerViewModel);
        }
        
        UserRegisterDto registerModelDto = _mapper.Map<UserRegisterDto>(registerViewModel);
        UserAuthResponse registerResult = await _authService.RegisterAsync(registerModelDto);

        if (!registerResult.IsSuccess)
        {
            if (registerResult.Errors is not null)
            {
                foreach (IdentityError error in registerResult.Errors)
                    ModelState.AddModelError(error.Code, error.Description);
            }
            else
            {
                ModelState.AddModelError("", registerResult.Message);
            }

            _notificationService.CustomErrorMessage(_stringLocalization["RegisterError"]);
            return View(registerViewModel);
        }
        
        _notificationService.CustomSuccessMessage(_stringLocalization["RegisterSuccess"]);
        return RedirectToAction(nameof(ConfirmEmail));
    }

    [HttpGet]
    [Unauthorized]
    public IActionResult Login(string? returnUrl)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Unauthorized]
    public async Task<IActionResult> Login(LoginViewModel loginViewModel, string? returnUrl)
    {
        returnUrl ??= Url.Content("~/");

        if (!ModelState.IsValid)
        {
            _notificationService.CustomErrorMessage(_stringLocalization["LoginError"]);
            return View(loginViewModel);
        }

        UserLoginDto loginModelDto = _mapper.Map<UserLoginDto>(loginViewModel);
        UserAuthResponse loginResult = await _authService.LoginAsync(loginModelDto);
        
        if (!loginResult.IsSuccess)
        {
            ModelState.AddModelError("", loginResult.Message);
            _notificationService.CustomErrorMessage(_stringLocalization["LoginError"]);
            return View(loginViewModel);
        }
        
        _notificationService.CustomSuccessMessage(_stringLocalization["LoginSuccess"]);
        return RedirectToLocal(returnUrl);
    }
    
    [HttpGet]
    [Unauthorized]
    public IActionResult ConfirmEmail()
    {
        return View();
    }

    [HttpGet]
    [Unauthorized]
    public async Task<IActionResult> ConfirmEmailResult([FromQuery] TokenValueDto<string> tokenValueDto)
    {
        if (tokenValueDto.Value is null || 
            string.IsNullOrWhiteSpace(tokenValueDto.Value) || string.IsNullOrWhiteSpace(tokenValueDto.Token))
        {
            _notificationService.CustomErrorMessage(_stringLocalization["UserNotFoundError"]);
            return RedirectToAction(nameof(Login));
        }
        
        UserAuthResponse result = await _authService.ConfirmEmailAsync(tokenValueDto);
        
        if (!result.IsSuccess)
        {
            if (result.Errors is not null)
            {
                foreach (IdentityError error in result.Errors)
                    ModelState.AddModelError(error.Code, error.Description);
            }
            else
            {
                ModelState.AddModelError("", result.Message);
            }

            _notificationService.CustomErrorMessage(_stringLocalization["ConfirmEmailError"]);
            return View();
        }

        _notificationService.CustomSuccessMessage(_stringLocalization["ConfirmEmailSuccess"]);
        return View();
    }
    
    [HttpGet]
    [Unauthorized]
    public IActionResult RemindPasswordResult()
    {
        return View();
    }
    
    [HttpGet]
    [Unauthorized]
    public IActionResult RemindPassword()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Unauthorized]
    public async Task<IActionResult> RemindPassword(RemindPasswordViewModel forgetPasswordViewModel)
    {
        if (!ModelState.IsValid || string.IsNullOrWhiteSpace(forgetPasswordViewModel.Email))
        {
            _notificationService.CustomErrorMessage(_stringLocalization["UserNotFoundError"]);
            return View(forgetPasswordViewModel);
        }
        
        RemindPasswordDto forgetPasswordDto = _mapper.Map<RemindPasswordDto>(forgetPasswordViewModel);
        UserAuthResponse forgetPasswordResult = await _authService.RemindPasswordAsync(forgetPasswordDto);
        
        if (!forgetPasswordResult.IsSuccess)
        {
            ModelState.AddModelError("", forgetPasswordResult.Message);
            _notificationService.CustomErrorMessage(_stringLocalization["RemindPasswordError"]);
            return View(forgetPasswordViewModel);
        }
        
        _notificationService.CustomSuccessMessage(_stringLocalization["RemindPasswordSuccess"]);
        return RedirectToAction(nameof(RemindPasswordResult));
    }
    
    [HttpGet]
    [Unauthorized]
    public IActionResult ResetPasswordResult()
    {
        return View();
    }
    
    [HttpGet]
    [Unauthorized]
    public IActionResult ResetPassword([FromQuery] TokenValueDto<string> tokenValueDto)
    {
        if (tokenValueDto.Value is null 
            || string.IsNullOrWhiteSpace(tokenValueDto.Value) || string.IsNullOrWhiteSpace(tokenValueDto.Token))
        {
            _notificationService.CustomErrorMessage(_stringLocalization["UserNotFoundError"]);
            return RedirectToAction(nameof(Login));
        }

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Unauthorized]
    public async Task<IActionResult> ResetPassword(ResetPasswordViewModel resetPasswordViewModel)
    {
        if (!ModelState.IsValid)
        {
            _notificationService.CustomErrorMessage(_stringLocalization["ResetPasswordError"]);
            return View(resetPasswordViewModel);
        }
        
        ResetPasswordDto resetPasswordDto = _mapper.Map<ResetPasswordDto>(resetPasswordViewModel);
        UserAuthResponse resetPasswordResult = await _authService.ResetPasswordAsync(resetPasswordDto);
        
        if (!resetPasswordResult.IsSuccess)
        {
            if (resetPasswordResult.Errors is not null)
            {
                foreach (IdentityError error in resetPasswordResult.Errors)
                    ModelState.AddModelError(error.Code, error.Description);
            }
            else
            {
                ModelState.AddModelError("", resetPasswordResult.Message);
            }

            _notificationService.CustomErrorMessage(_stringLocalization["ResetPasswordError"]);
            return View(resetPasswordViewModel);
        }

        _notificationService.CustomSuccessMessage(_stringLocalization["ResetPasswordSuccess"]);
        return RedirectToAction(nameof(ResetPasswordResult));
    }
    
    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        HttpContext.Session.Clear();
        await _authService.LogoutAsync();
        _notificationService.CustomSuccessMessage(_stringLocalization["LogoutSuccess"]);
        return RedirectToAction(nameof(Login));
    }

    [HttpPost]
    public IActionResult SetCulture(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions {Expires = DateTimeOffset.UtcNow.AddDays(30)}
        );
        
        return LocalRedirect(returnUrl);
    }
    
    private IActionResult RedirectToLocal(string? returnUrl)
    {
        if (Url.IsLocalUrl(returnUrl))
            return Redirect(returnUrl);
    
        return RedirectToAction(nameof(Index), "Home");
    }
}

src/MethodicalSupportDisciplines.MVC/Controllers/StudentController.cs
using MethodicalSupportDisciplines.BLL.Interfaces;
using MethodicalSupportDisciplines.BLL.Interfaces.Learning;
using MethodicalSupportDisciplines.MVC.Controllers.Base;
using MethodicalSupportDisciplines.Shared.AdditionalModels;
using MethodicalSupportDisciplines.Shared.Constants;
using MethodicalSupportDisciplines.Shared.Responses.Services;
using MethodicalSupportDisciplines.Shared.Responses.Services.LearningServicesResponses;
using MethodicalSupportDisciplines.Shared.ViewModels.Learning;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MethodicalSupportDisciplines.MVC.Controllers;

[Authorize(Roles = ApplicationRoles.StudentRole)]
public class StudentController : BaseController
{
    private readonly IDisciplineService _disciplineService;
    private readonly IUsersService _usersService;

    public StudentController(INotificationService notificationService, IDisciplineService disciplineService,
        IUsersService usersService) :
        base(
            notificationService)
    {
        _disciplineService = disciplineService;
        _usersService = usersService;
    }

    public async Task<IActionResult> Disciplines(QueryParameters queryParameters)
    {
        string currentUserId = GetUserId();
        string username = GetUsername();

        DisciplineServiceResponse getResult =
            await _disciplineService.GetDisciplinesForStudentAsync(currentUserId, queryParameters);

        if (!getResult.IsSuccess)
        {
            NotificationService.CustomErrorMessage(getResult.Message);
            return RedirectToAction(nameof(Index), "Home");
        }

        StudentDisciplinesViewModel viewModel = new StudentDisciplinesViewModel
        {
            DisciplineGroups = getResult.DisciplineGroups,
            Username = username,
            CurrentController = GetCurrentControllerName(),
            CurrentAction = GetCurrentActionName(),
            QueryParameters = queryParameters,
            Pages = getResult.Pages,
            ItemsCount = getResult.ItemsCount,
            PageCount = getResult.PageCount
        };

        IActionResult actionResult = CheckQueryParametersForPageBaseCondition(
            ref queryParameters, viewModel, getResult);

        return actionResult;
    }

    public async Task<IActionResult> DisciplineData(int disciplineId)
    {
        string currentUserId = GetUserId();

        DisciplineServiceResponse getDisciplineResult =
            await _disciplineService.GetDisciplineForStudentByIdAsync(disciplineId, currentUserId);

        if (!getDisciplineResult.IsSuccess)
        {
            NotificationService.CustomErrorMessage(getDisciplineResult.Message);
            return RedirectToAction(nameof(Disciplines));
        }

        StudentDisciplinesViewModel viewModel = new StudentDisciplinesViewModel
        {
            Discipline = getDisciplineResult.Discipline
        };

        return View(viewModel);
    }

    public async Task<IActionResult> Account()
    {
        string userId = GetUserId();

        UsersServiceResponse response = await _usersService.GetStudentUserAccountAsync(userId);

        if (!response.IsSuccess)
        {
            NotificationService.CustomErrorMessage(response.Message);
            return RedirectToAction(nameof(Index), "Home");
        }

        return View(response.StudentUser);
    }
}

src/MethodicalSupportDisciplines.MVC/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="120x120" href="~/img/icons/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/img/icons/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/img/icons/favicon/favicon-16x16.png">
<link rel="manifest" href="~/img/icons/favicon/site.webmanifest">
<link rel="mask-icon" href="~/img/icons/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

src/MethodicalSupportDisciplines.MVC/Views/Shared/_Header.cshtml
@using System.Globalization
@using MethodicalSupportDisciplines.Shared.Constants
@addTagHelper *, MethodicalSupportDisciplines.MVC

@{
    string returnUrl = string.IsNullOrEmpty(Context.Request.Path)
        ? "~/"
        : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<header class="navigation-wrap bg-light header-main">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-md navbar">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <h2>
                            <span class="navbar-brand__name">M.S.D</span>
                        </h2>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            <ul class="navbar-nav ml-auto py-4 py-md-0">
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a asp-controller="Home" asp-action="Index" class="nav-link" is-active-header-route>@ViewLocalization["Home"]</a>
                                </li>
                                @if (User.IsInRole(ApplicationRoles.AdminRole))
                                {
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Admin" asp-action="GuestUsers" class="nav-link" is-active-header-route>@ViewLocalization["GuestUsers"]</a>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Admin" asp-action="TeacherUsers" class="nav-link" is-active-header-route>@ViewLocalization["TeacherUsers"]</a>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Admin" asp-action="StudentUsers" class="nav-link" is-active-header-route>@ViewLocalization["StudentUsers"]</a>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Admin" asp-action="Disciplines" class="nav-link" is-active-header-route>@ViewLocalization["Disciplines"]</a>
                                    </li>
                                }
                                @if (User.IsInRole(ApplicationRoles.TeacherRole))
                                {
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Teacher" asp-action="Disciplines" class="nav-link" is-active-header-route>@ViewLocalization["Disciplines"]</a>
                                    </li>
                                }
                                @if (User.IsInRole(ApplicationRoles.StudentRole))
                                {
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a asp-controller="Student" asp-action="Disciplines" class="nav-link" is-active-header-route>@ViewLocalization["Disciplines"]</a>
                                    </li>
                                }
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false"
                                       href="#">
                                        @ViewLocalization["Account"]
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole(ApplicationRoles.StudentRole))
                                        {
                                            <a class="dropdown-item"
                                               asp-controller="Student" asp-action="Account"
                                               is-active-header-route>
                                                @ViewLocalization["Account"]
                                            </a>
                                        }
                                        @if (User.IsInRole(ApplicationRoles.TeacherRole))
                                        {
                                            <a class="dropdown-item"
                                               asp-controller="Teacher" asp-action="Account"
                                               is-active-header-route>
                                                @ViewLocalization["Account"]
                                            </a>
                                        }
                                        <form method="post" asp-controller="Auth" asp-action="SetCulture"
                                              asp-route-returnUrl="@returnUrl" asp-antiforgery="true">
                                            @if (CultureInfo.CurrentCulture.Equals(new CultureInfo("en")))
                                            {
                                                <input name="culture" type="hidden" value="uk">
                                                <button type="submit" class="dropdown-item">Змінити на українську</button>
                                            }
                                            else
                                            {
                                                <input name="culture" type="hidden" value="en">
                                                <button type="submit" class="dropdown-item">Switch to English</button>
                                            }
                                        </form>
                                        <a asp-controller="Auth" asp-action="Logout" class="dropdown-item">@ViewLocalization["Logout"]</a>
                                    </div>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav ml-auto py-4 py-md-0">
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <form method="post" asp-controller="Auth" asp-action="SetCulture"
                                          asp-route-returnUrl="@returnUrl" asp-antiforgery="true">
                                        @if (CultureInfo.CurrentCulture.Equals(new CultureInfo("en")))
                                        {
                                            <input name="culture" type="hidden" value="uk">
                                            <button type="submit" class="nav-link">Змінити на українську</button>
                                        }
                                        else
                                        {
                                            <input name="culture" type="hidden" value="en">
                                            <button type="submit" class="nav-link">Switch to English</button>
                                        }
                                    </form>
                                </li>
                            </ul>
                        }
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

src/MethodicalSupportDisciplines.MVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @await Html.PartialAsync("_Favicons")
    
    <title>@ViewData["Title"]</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/libs/sweetAlert/sweetalert2.min.css">

    <environment names="Development">
        <link rel="stylesheet" href="~/css/style.css">
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="~/css/style.min.css">
    </environment>
</head>
<body>

@await Html.PartialAsync("_Header")

<div class="main-container">
    @RenderBody()
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/0172dea2c0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="~/libs/sweetAlert/sweetalert2.min.js"></script>

<environment names="Development">
    <script src="~/js/components/main/header.component.js"></script>
    <script type="module" src="~/js/services/notification.service.js"></script>
</environment>
<environment names="Production">
    <script src="~/js/components/main/header.component.min.js"></script>
    <script type="module" src="~/js/services/notification.service.min.js"></script>
</environment>

@await Component.InvokeAsync("Notyf")
</body>
</html>

src/MethodicalSupportDisciplines.MVC/Views/Shared/_MainFormsBackground.cshtml
<div class="header-waves">
    <div class="content-before-waves"></div>
    <div>
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
            <defs>
                <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
            </defs>
            <g class="parallax">
                <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7)"/>
                <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)"/>
                <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)"/>
                <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff"/>
            </g>
        </svg>
    </div>
</div>